// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd4FU-5lT9ngenB3l7CTS4xUtpkHEQJm0',
    appId: '1:206526653884:web:0810ef57b36222fe6877b9',
    messagingSenderId: '206526653884',
    projectId: 'krishishop-c1de8',
    authDomain: 'krishishop-c1de8.firebaseapp.com',
    storageBucket: 'krishishop-c1de8.appspot.com',
    measurementId: 'G-YPFMQCSESW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv9Fqr5LSIhzEQ98X9A1RjvN7XnblL7m4',
    appId: '1:206526653884:android:385ee322715a483e6877b9',
    messagingSenderId: '206526653884',
    projectId: 'krishishop-c1de8',
    storageBucket: 'krishishop-c1de8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Mmy-78qEzyzQD3nmZ6GRj5N82Xvhg7w',
    appId: '1:206526653884:ios:48f9208ac8789d6c6877b9',
    messagingSenderId: '206526653884',
    projectId: 'krishishop-c1de8',
    storageBucket: 'krishishop-c1de8.appspot.com',
    iosClientId: '206526653884-hh2f6dvi8h9uk9lrnq3l1q0ffsui7dqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.krishishop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8Mmy-78qEzyzQD3nmZ6GRj5N82Xvhg7w',
    appId: '1:206526653884:ios:3acb5470775f26656877b9',
    messagingSenderId: '206526653884',
    projectId: 'krishishop-c1de8',
    storageBucket: 'krishishop-c1de8.appspot.com',
    iosClientId: '206526653884-5u1b27alcc1g5npa7fruehni0u1o671e.apps.googleusercontent.com',
    iosBundleId: 'com.example.krishishop.RunnerTests',
  );
}
